import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

// Helper to verify project ownership
async function verifyProjectOwnership(
  ctx: { auth: { getUserIdentity: () => Promise<{ subject: string } | null> }; db: { get: (id: unknown) => Promise<{ userId: { toString: () => string } } | null>; query: (table: string) => unknown } },
  projectId: unknown
) {
  const identity = await ctx.auth.getUserIdentity();
  if (!identity) {
    throw new Error("Unauthorized: not authenticated");
  }

  // @ts-expect-error - Types will be generated by `npx convex dev`
  const project = await ctx.db.get(projectId);
  if (!project) {
    throw new Error("Project not found");
  }

  // Get user by clerkId to compare userId
  const user = await ctx.db
    // @ts-expect-error - Types will be generated by `npx convex dev`
    .query("users")
    // @ts-expect-error - Types will be generated by `npx convex dev`
    .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
    .first();

  if (!user || project.userId.toString() !== user._id.toString()) {
    throw new Error("Unauthorized: you do not own this project");
  }

  return { identity, project, user };
}

// List all projects for a user - uses auth context instead of client-supplied userId
export const listByUser = query({
  args: {},
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      return [];
    }

    // Get user by clerkId
    const user = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();

    if (!user) {
      return [];
    }

    return await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("projects")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .order("desc")
      .collect();
  },
});

// Get a single project by ID - with ownership check
export const getById = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      return null;
    }

    const project = await ctx.db.get(args.projectId);
    if (!project) return null;

    // Get user by clerkId to verify ownership
    const user = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();

    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!user || project.userId.toString() !== user._id.toString()) {
      return null; // Don't leak project existence to non-owners
    }

    return project;
  },
});

// Get project with related data (videos, voice profile, concept) - with ownership check
export const getWithDetails = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      return null;
    }

    const project = await ctx.db.get(args.projectId);
    if (!project) return null;

    // Get user by clerkId to verify ownership
    const user = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();

    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!user || project.userId.toString() !== user._id.toString()) {
      return null; // Don't leak project existence to non-owners
    }

    // Get associated videos
    const videos = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    // Get voice profile if exists
    // @ts-expect-error - Types will be generated by `npx convex dev`
    const voiceProfile = project.voiceProfileId
      // @ts-expect-error - Types will be generated by `npx convex dev`
      ? await ctx.db.get(project.voiceProfileId)
      : null;

    // Get selected concept if exists
    // @ts-expect-error - Types will be generated by `npx convex dev`
    const selectedConcept = project.selectedConceptId
      // @ts-expect-error - Types will be generated by `npx convex dev`
      ? await ctx.db.get(project.selectedConceptId)
      : null;

    // Get chapters
    const chapters = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("chapters")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    return {
      ...project,
      videos,
      voiceProfile,
      selectedConcept,
      // @ts-expect-error - Types will be generated by `npx convex dev`
      chapters: chapters.sort((a, b) => a.orderIndex - b.orderIndex),
    };
  },
});

// Create a new project - uses auth context to get userId
export const create = mutation({
  args: {
    name: v.string(),
    description: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Unauthorized: not authenticated");
    }

    // Get user by clerkId
    const user = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();

    if (!user) {
      throw new Error("User not found");
    }

    const now = Date.now();

    // @ts-expect-error - Types will be generated by `npx convex dev`
    return await ctx.db.insert("projects", {
      userId: user._id,
      name: args.name,
      description: args.description,
      status: "draft",
      selectedVideoIds: [],
      createdAt: now,
      updatedAt: now,
    });
  },
});

// Update project - with ownership verification
export const update = mutation({
  args: {
    projectId: v.id("projects"),
    name: v.optional(v.string()),
    description: v.optional(v.string()),
    status: v.optional(
      v.union(
        v.literal("draft"),
        v.literal("analyzing"),
        v.literal("structuring"),
        v.literal("writing"),
        v.literal("editing"),
        v.literal("completed")
      )
    ),
    selectedVideoIds: v.optional(v.array(v.id("videos"))),
    voiceProfileId: v.optional(v.id("voiceProfiles")),
    selectedConceptId: v.optional(v.id("bookConcepts")),
    coverId: v.optional(v.id("covers")),
  },
  handler: async (ctx, args) => {
    // Verify ownership
    // @ts-expect-error - Helper uses dynamic typing
    await verifyProjectOwnership(ctx, args.projectId);

    const { projectId, ...updates } = args;

    // Filter out undefined values
    const cleanUpdates = Object.fromEntries(
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      Object.entries(updates).filter(([_, value]) => value !== undefined)
    );

    await ctx.db.patch(projectId, {
      ...cleanUpdates,
      updatedAt: Date.now(),
    });
  },
});

// Add videos to project - with ownership verification
export const addVideos = mutation({
  args: {
    projectId: v.id("projects"),
    videoIds: v.array(v.id("videos")),
  },
  handler: async (ctx, args) => {
    // Verify ownership
    // @ts-expect-error - Helper uses dynamic typing
    const { project } = await verifyProjectOwnership(ctx, args.projectId);

    // @ts-expect-error - Types will be generated by `npx convex dev`
    const existingIds = new Set(project.selectedVideoIds);
    const newIds = args.videoIds.filter((id) => !existingIds.has(id));

    await ctx.db.patch(args.projectId, {
      // @ts-expect-error - Types will be generated by `npx convex dev`
      selectedVideoIds: [...project.selectedVideoIds, ...newIds],
      updatedAt: Date.now(),
    });

    // Update videos to link to this project
    for (const videoId of newIds) {
      await ctx.db.patch(videoId, { projectId: args.projectId });
    }
  },
});

// Remove videos from project - with ownership verification
export const removeVideos = mutation({
  args: {
    projectId: v.id("projects"),
    videoIds: v.array(v.id("videos")),
  },
  handler: async (ctx, args) => {
    // Verify ownership
    // @ts-expect-error - Helper uses dynamic typing
    const { project } = await verifyProjectOwnership(ctx, args.projectId);

    const removeSet = new Set(args.videoIds);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    const remainingIds = project.selectedVideoIds.filter((id) => !removeSet.has(id));

    await ctx.db.patch(args.projectId, {
      selectedVideoIds: remainingIds,
      updatedAt: Date.now(),
    });

    // Unlink videos from project
    for (const videoId of args.videoIds) {
      await ctx.db.patch(videoId, { projectId: undefined });
    }
  },
});

// Delete project and all related data - with ownership verification
export const deleteProject = mutation({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    // Verify ownership
    // @ts-expect-error - Helper uses dynamic typing
    await verifyProjectOwnership(ctx, args.projectId);

    // Delete related videos
    const videos = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();
    for (const video of videos) {
      // @ts-expect-error - Types will be generated by `npx convex dev`
      await ctx.db.delete(video._id);
    }

    // Delete voice profiles
    const voiceProfiles = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("voiceProfiles")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();
    for (const vp of voiceProfiles) {
      // @ts-expect-error - Types will be generated by `npx convex dev`
      await ctx.db.delete(vp._id);
    }

    // Delete book concepts
    const concepts = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("bookConcepts")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();
    for (const concept of concepts) {
      // @ts-expect-error - Types will be generated by `npx convex dev`
      await ctx.db.delete(concept._id);
    }

    // Delete chapters and their drafts
    const chapters = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("chapters")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();
    for (const chapter of chapters) {
      const drafts = await ctx.db
        // @ts-expect-error - Types will be generated by `npx convex dev`
        .query("chapterDrafts")
        // @ts-expect-error - Types will be generated by `npx convex dev`
        .withIndex("by_chapter", (q) => q.eq("chapterId", chapter._id))
        .collect();
      for (const draft of drafts) {
        // @ts-expect-error - Types will be generated by `npx convex dev`
        await ctx.db.delete(draft._id);
      }
      // @ts-expect-error - Types will be generated by `npx convex dev`
      await ctx.db.delete(chapter._id);
    }

    // Delete covers
    const covers = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("covers")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();
    for (const cover of covers) {
      // @ts-expect-error - Types will be generated by `npx convex dev`
      await ctx.db.delete(cover._id);
    }

    // Finally delete the project
    await ctx.db.delete(args.projectId);
  },
});
