import { v } from "convex/values";
import { mutation, query, internalQuery, internalMutation } from "./_generated/server";

// Helper to strip sensitive fields from user object
// @ts-expect-error - Types will be generated by `npx convex dev`
function sanitizeUser(user) {
  if (!user) return null;
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { youtubeTokens, ...safeUser } = user;
  return safeUser;
}

// Get user by Clerk ID - INTERNAL ONLY (for server-side use like webhooks)
export const getByClerkId = internalQuery({
  args: { clerkId: v.string() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", args.clerkId))
      .first();
  },
});

// Get current user (requires auth context) - returns sanitized user without tokens
export const getCurrentUser = query({
  args: {},
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      return null;
    }

    const user = await ctx.db
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();

    return sanitizeUser(user);
  },
});

// Create or update user from Clerk webhook (internal - called from webhook handler)
export const upsertFromClerk = internalMutation({
  args: {
    clerkId: v.string(),
    email: v.string(),
    name: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const existingUser = await ctx.db
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", args.clerkId))
      .first();

    const now = Date.now();

    if (existingUser) {
      await ctx.db.patch(existingUser._id, {
        email: args.email,
        name: args.name,
        imageUrl: args.imageUrl,
        updatedAt: now,
      });
      return existingUser._id;
    }

    return await ctx.db.insert("users", {
      clerkId: args.clerkId,
      email: args.email,
      name: args.name,
      imageUrl: args.imageUrl,
      youtubeConnected: false,
      createdAt: now,
      updatedAt: now,
    });
  },
});

// Update YouTube connection status - with auth guard
export const updateYouTubeConnection = mutation({
  args: {
    userId: v.id("users"),
    youtubeTokens: v.object({
      accessToken: v.string(),
      refreshToken: v.string(),
      expiresAt: v.number(),
    }),
  },
  handler: async (ctx, args) => {
    // Auth guard: verify caller owns this user record
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Unauthorized: not authenticated");
    }

    const user = await ctx.db.get(args.userId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!user || user.clerkId !== identity.subject) {
      throw new Error("Unauthorized: cannot modify another user's record");
    }

    await ctx.db.patch(args.userId, {
      youtubeConnected: true,
      youtubeTokens: args.youtubeTokens,
      updatedAt: Date.now(),
    });
  },
});

// Internal version for server-side YouTube connection updates (from API routes)
export const updateYouTubeConnectionInternal = internalMutation({
  args: {
    userId: v.id("users"),
    youtubeTokens: v.object({
      accessToken: v.string(),
      refreshToken: v.string(),
      expiresAt: v.number(),
    }),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.userId, {
      youtubeConnected: true,
      youtubeTokens: args.youtubeTokens,
      updatedAt: Date.now(),
    });
  },
});

// Disconnect YouTube - with auth guard
export const disconnectYouTube = mutation({
  args: { userId: v.id("users") },
  handler: async (ctx, args) => {
    // Auth guard: verify caller owns this user record
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Unauthorized: not authenticated");
    }

    const user = await ctx.db.get(args.userId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!user || user.clerkId !== identity.subject) {
      throw new Error("Unauthorized: cannot modify another user's record");
    }

    await ctx.db.patch(args.userId, {
      youtubeConnected: false,
      youtubeTokens: undefined,
      updatedAt: Date.now(),
    });
  },
});

// Delete user - internal only (called from Clerk webhook)
export const deleteUser = internalMutation({
  args: { clerkId: v.string() },
  handler: async (ctx, args) => {
    const user = await ctx.db
      .query("users")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", args.clerkId))
      .first();

    if (user) {
      await ctx.db.delete(user._id);
    }
  },
});
