import { v } from "convex/values";
import { mutation, query, internalQuery, internalMutation } from "./_generated/server";

// Helper to get current user from auth context
async function getCurrentUser(ctx: {
  auth: { getUserIdentity: () => Promise<{ subject: string } | null> };
  db: { query: (table: string) => unknown };
}) {
  const identity = await ctx.auth.getUserIdentity();
  if (!identity) {
    return null;
  }

  const user = await ctx.db
    // @ts-expect-error - Types will be generated by `npx convex dev`
    .query("users")
    // @ts-expect-error - Types will be generated by `npx convex dev`
    .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
    .first();

  return user;
}

// List videos for the current user
export const listByUser = query({
  args: {},
  handler: async (ctx) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      return [];
    }

    return await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_user", (q) => q.eq("userId", user._id))
      .order("desc")
      .collect();
  },
});

// List videos for a project - with ownership check
export const listByProject = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      return [];
    }

    // Verify project ownership
    const project = await ctx.db.get(args.projectId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!project || project.userId.toString() !== user._id.toString()) {
      return [];
    }

    return await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();
  },
});

// Get a single video by ID - with ownership check
export const getById = query({
  args: { videoId: v.id("videos") },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      return null;
    }

    const video = await ctx.db.get(args.videoId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!video || video.userId.toString() !== user._id.toString()) {
      return null;
    }

    return video;
  },
});

// Get video by YouTube ID - scoped to current user
export const getByYouTubeId = query({
  args: { youtubeId: v.string() },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      return null;
    }

    return await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_user_youtube_id", (q) =>
        q.eq("userId", user._id).eq("youtubeId", args.youtubeId)
      )
      .first();
  },
});

// Create a new video - uses auth context to get userId
export const create = mutation({
  args: {
    projectId: v.optional(v.id("projects")),
    youtubeId: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    thumbnailUrl: v.optional(v.string()),
    duration: v.optional(v.string()),
    publishedAt: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      throw new Error("Unauthorized: not authenticated");
    }

    // If projectId is provided, verify ownership
    if (args.projectId) {
      const project = await ctx.db.get(args.projectId);
      // @ts-expect-error - Types will be generated by `npx convex dev`
      if (!project || project.userId.toString() !== user._id.toString()) {
        throw new Error("Unauthorized: you do not own this project");
      }
    }

    const now = Date.now();

    // @ts-expect-error - Types will be generated by `npx convex dev`
    return await ctx.db.insert("videos", {
      userId: user._id,
      projectId: args.projectId,
      youtubeId: args.youtubeId,
      title: args.title,
      description: args.description,
      thumbnailUrl: args.thumbnailUrl,
      duration: args.duration,
      publishedAt: args.publishedAt,
      transcriptStatus: "pending",
      createdAt: now,
      updatedAt: now,
    });
  },
});

// Batch create videos - with user-scoped deduplication
export const createBatch = mutation({
  args: {
    projectId: v.optional(v.id("projects")),
    videos: v.array(
      v.object({
        youtubeId: v.string(),
        title: v.string(),
        description: v.optional(v.string()),
        thumbnailUrl: v.optional(v.string()),
        duration: v.optional(v.string()),
        publishedAt: v.optional(v.string()),
      })
    ),
  },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      throw new Error("Unauthorized: not authenticated");
    }

    // If projectId is provided, verify ownership
    if (args.projectId) {
      const project = await ctx.db.get(args.projectId);
      // @ts-expect-error - Types will be generated by `npx convex dev`
      if (!project || project.userId.toString() !== user._id.toString()) {
        throw new Error("Unauthorized: you do not own this project");
      }
    }

    const now = Date.now();
    const videoIds = [];

    for (const video of args.videos) {
      // Check if video already exists FOR THIS USER using compound index
      const existing = await ctx.db
        // @ts-expect-error - Types will be generated by `npx convex dev`
        .query("videos")
        // @ts-expect-error - Types will be generated by `npx convex dev`
        .withIndex("by_user_youtube_id", (q) =>
          q.eq("userId", user._id).eq("youtubeId", video.youtubeId)
        )
        .first();

      if (existing) {
        // @ts-expect-error - Types will be generated by `npx convex dev`
        videoIds.push(existing._id);
      } else {
        // @ts-expect-error - Types will be generated by `npx convex dev`
        const id = await ctx.db.insert("videos", {
          userId: user._id,
          projectId: args.projectId,
          youtubeId: video.youtubeId,
          title: video.title,
          description: video.description,
          thumbnailUrl: video.thumbnailUrl,
          duration: video.duration,
          publishedAt: video.publishedAt,
          transcriptStatus: "pending",
          createdAt: now,
          updatedAt: now,
        });
        videoIds.push(id);
      }
    }

    return videoIds;
  },
});

// Update transcript status - with ownership check
export const updateTranscriptStatus = mutation({
  args: {
    videoId: v.id("videos"),
    status: v.union(
      v.literal("pending"),
      v.literal("fetching"),
      v.literal("completed"),
      v.literal("failed"),
      v.literal("unavailable")
    ),
    transcript: v.optional(v.string()),
    error: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      throw new Error("Unauthorized: not authenticated");
    }

    const video = await ctx.db.get(args.videoId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!video || video.userId.toString() !== user._id.toString()) {
      throw new Error("Unauthorized: you do not own this video");
    }

    await ctx.db.patch(args.videoId, {
      transcriptStatus: args.status,
      transcript: args.transcript,
      transcriptError: args.error,
      updatedAt: Date.now(),
    });
  },
});

// Update video - with ownership check
export const update = mutation({
  args: {
    videoId: v.id("videos"),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    projectId: v.optional(v.id("projects")),
  },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      throw new Error("Unauthorized: not authenticated");
    }

    const video = await ctx.db.get(args.videoId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!video || video.userId.toString() !== user._id.toString()) {
      throw new Error("Unauthorized: you do not own this video");
    }

    // If updating projectId, verify ownership of target project
    if (args.projectId) {
      const project = await ctx.db.get(args.projectId);
      // @ts-expect-error - Types will be generated by `npx convex dev`
      if (!project || project.userId.toString() !== user._id.toString()) {
        throw new Error("Unauthorized: you do not own the target project");
      }
    }

    const { videoId, ...updates } = args;

    const cleanUpdates = Object.fromEntries(
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      Object.entries(updates).filter(([_, value]) => value !== undefined)
    );

    await ctx.db.patch(videoId, {
      ...cleanUpdates,
      updatedAt: Date.now(),
    });
  },
});

// Delete video - with ownership check
export const deleteVideo = mutation({
  args: { videoId: v.id("videos") },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      throw new Error("Unauthorized: not authenticated");
    }

    const video = await ctx.db.get(args.videoId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!video || video.userId.toString() !== user._id.toString()) {
      throw new Error("Unauthorized: you do not own this video");
    }

    await ctx.db.delete(args.videoId);
  },
});

// Get videos with pending transcripts for a project - with ownership check
export const getPendingTranscripts = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      return [];
    }

    // Verify project ownership
    const project = await ctx.db.get(args.projectId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!project || project.userId.toString() !== user._id.toString()) {
      return [];
    }

    const videos = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    // @ts-expect-error - Types will be generated by `npx convex dev`
    return videos.filter(
      (v: { transcriptStatus: string }) => v.transcriptStatus === "pending" || v.transcriptStatus === "fetching"
    );
  },
});

// Get transcript stats for a project - with ownership check
export const getTranscriptStats = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    // @ts-expect-error - Helper uses dynamic typing
    const user = await getCurrentUser(ctx);
    if (!user) {
      return null;
    }

    // Verify project ownership
    const project = await ctx.db.get(args.projectId);
    // @ts-expect-error - Types will be generated by `npx convex dev`
    if (!project || project.userId.toString() !== user._id.toString()) {
      return null;
    }

    const videos = await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    return {
      total: videos.length,
      // @ts-expect-error - Types will be generated by `npx convex dev`
      completed: videos.filter((v) => v.transcriptStatus === "completed").length,
      // @ts-expect-error - Types will be generated by `npx convex dev`
      pending: videos.filter((v) => v.transcriptStatus === "pending").length,
      // @ts-expect-error - Types will be generated by `npx convex dev`
      fetching: videos.filter((v) => v.transcriptStatus === "fetching").length,
      // @ts-expect-error - Types will be generated by `npx convex dev`
      failed: videos.filter((v) => v.transcriptStatus === "failed").length,
      // @ts-expect-error - Types will be generated by `npx convex dev`
      unavailable: videos.filter((v) => v.transcriptStatus === "unavailable").length,
    };
  },
});

// ============================================
// Internal functions for server-side use only
// ============================================

// List videos for a project - INTERNAL (no auth check, for server-side use)
export const listByProjectInternal = internalQuery({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    return await ctx.db
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .query("videos")
      // @ts-expect-error - Types will be generated by `npx convex dev`
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();
  },
});

// Update transcript status - INTERNAL (no auth check, for server-side use)
export const updateTranscriptStatusInternal = internalMutation({
  args: {
    videoId: v.id("videos"),
    status: v.union(
      v.literal("pending"),
      v.literal("fetching"),
      v.literal("completed"),
      v.literal("failed"),
      v.literal("unavailable")
    ),
    transcript: v.optional(v.string()),
    error: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.videoId, {
      transcriptStatus: args.status,
      transcript: args.transcript,
      transcriptError: args.error,
      updatedAt: Date.now(),
    });
  },
});
